services:
  db:
    image: postgres:16.1-alpine3.18
    restart: always
    environment:
      POSTGRES_DB: "upload_data_db"
      POSTGRES_USER: "pguser"
      POSTGRES_PASSWORD: "12345"
    volumes:
      - .:/docker-entrypoint-initdb.d
    ports:
      - "6432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U pguser -d upload_data_db" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
  app:
    build: .
    depends_on:
      - db
    environment:
      DB_PORT: "5432"
      DB_NAME: "upload_data_db"
      DB_USER: "pguser"
      DB_PASSWORD: "12345"
      DB_HOST: db
    volumes:
      - .:/app
    ports:
      - "8000:8000"